services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: HeyItsMinx11
      POSTGRES_DB: porto-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d porto-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgres://admin:HeyItsMinx11@database:5432/porto-db?sslmode=disable
      - up
    depends_on:
      database:
        condition: service_healthy

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_USER=admin
      - DB_PASSWORD=HeyItsMinx11
      - DB_NAME=porto-db
      - DB_PORT=5432
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: